export const SEMINAR_SAVE_FAILED = 'SEMINAR_SAVE_FAILED'
export const SEMINAR_ATTEND_START = 'SEMINAR_ATTEND_START'
export const SEMINAR_ATTEND_ERROR = 'SEMINAR_ATTEND_ERROR'
export const SEMINAR_ATTEND_SUCCESS = 'SEMINAR_ATTEND_SUCCESS'
